imports:
  - { resource: '../../var/config/' }

tools:
  #default:
  #  providedBy:
  #    name: some contractor
  #    street: some street + house number
  #    location: some city + zip
  #    vatId: #vatid
  #    country: #countryCode e.g. DE
  #    phone: #phone
  #    mail: #mail
  #    web: #web
  #    bank: #bank
  #    iban: #iban
  #    bic: #bic
  dompdf:
    #creator: Marc Eichenseher
    #producer: smoothie <hello@marceichenseher.com>
    #fontsDirectory: '%twig.default_path%/fonts/'
    #templateDirectory: '%twig.default_path%/pdf/'
    #exportDirectory: '%kernel.project_dir%/var/pdf/'
    fonts:
      - { file: Mulish/Mulish-Regular.ttf, style: { family: Mulish, style: normal, weight: 400 } }
      - { file: Mulish/Mulish-SemiBold.ttf, style: { family: Mulish, style: normal, weight: 500 } }
      - { file: Mulish/Mulish-Bold.ttf, style: { family: Mulish, style: normal, weight: 700 } }
      - { file: Mulish/Mulish-Black.ttf, style: { family: Mulish, style: normal, weight: 900 } }
