# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in ... available to be used as services
    Smoothie\ContractorTools\Symfony\:
        resource: '../src/Symfony'
        exclude:
            - '../src/Symfony/DependencyInjection/'
            - '../src/Symfony/Kernel.php'

    Smoothie\ContractorTools\Doctrine\:
        resource: '../src/Doctrine'

    Smoothie\ContractorTools\Contracts\:
        resource: '../src/Contracts'

    # TODO: Consider moving to extension and load those from the kernel
    Smoothie\ContractorTools\Timesheet\:
        resource: '../src/Timesheet'
